export const metadata = {
    title: 'About | Next Hero',
    description: 'Generated by create next app',
  }

const AboutPage = () => {
    return (
        <div className=" container mx-auto">
            <h2>This is about Page</h2>

        </div>
    );
};

export default AboutPage;