export const metadata = {
    title: 'AddProduct | DashBoard | Next Hero',
    description: 'Generated by create next app',
  }

const AddProduct = () => {
    return (
        <div>
            <h1>this is Add product page </h1>

        </div>
    );
};

export default AddProduct;